name: "Publish: {Service Name}"
run-name: Publish {Service Name} from tag = ${{ github.ref_name }} # This name is visible on the list of runs.

on:
  push:
    tags:
      - '{Service Name}/v*' # The job gets executed as soon as a new tag is released.

env:
  JFROG_CLI_LOG_LEVEL: DEBUG
  JFROG_SERVER: {Artifactory Server Name} # The Artifactory Server Name.
  WORKING_DIRECTORY: {Service Name} # If there is a mono repo structure then this flag helps to target the service folder.

jobs:
  publish:
    runs-on: [self-hosted, worker-small] # Specifies the machine that the job will run on. Can be gitHub hosted.

    steps:
    - name: Checkout Repository # Checkout Repository.
      uses: actions/checkout@v4

    - name: Setup JFrog CLI # Sets up JFrog Artifactory.
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_ENV_1: ${{ secrets.JF_SECRET_ENV_MAGPIE }} # The secrets contains the authentication details to Artifactory Server.

    - name: Show JFrog Config # Shows the Jfrog Artifactory config in use.
      shell: bash
      run: jf config show

    - name: Setup Maven Config # Sets up Maven Config
      shell: bash
      run: |
      # {local} here refers to the org's inhouse artifacts which the current service can utilize
        jf mvn-config \
          --repo-resolve-releases {local}-maven \   
          --repo-resolve-snapshots {local}-maven \
          --repo-deploy-releases libs-release \
          --repo-deploy-snapshots libs-snapshot \
          --server-id-deploy $JFROG_SERVER \
          --server-id-resolve $JFROG_SERVER

    - name: Setup JDK 8 # Sets Up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'corretto'
        cache: maven

    - name: Setup Maven Tool # Sets up Maven.
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.9.5

    - name: Build And Publish Maven Artifacts # Build and Publish the Artifacts
      shell: bash
      run: jf mvn -B clean deploy --show-version
      working-directory: ${{ env.WORKING_DIRECTORY }}

    - name: Publish Build Info # Publish Build Info
      shell: bash
      run: jf rt build-publish
      working-directory: ${{ env.WORKING_DIRECTORY }}
